import type { InventoryItem } from "./types"

export const dairyInventory: InventoryItem[] = [
  {
    id: "1",
    name: "Organic Whole Milk",
    category: "Milk",
    price: 4.99,
    stock: 45,
    image: "/placeholder.svg?height=300&width=300",
    description: "Fresh organic whole milk from grass-fed cows",
    origin: "Local Farms",
    allergens: "Milk",
  },
  {
    id: "2",
    name: "Aged Cheddar Cheese",
    category: "Cheese",
    price: 6.99,
    stock: 30,
    image: "/placeholder.svg?height=300&width=300",
    description: "Sharp cheddar aged for 12 months",
    origin: "Wisconsin",
    allergens: "Milk",
  },
  {
    id: "3",
    name: "Greek Yogurt",
    category: "Yogurt",
    price: 3.49,
    stock: 50,
    image: "/placeholder.svg?height=300&width=300",
    description: "Creamy Greek yogurt with live cultures",
    origin: "Greece",
    allergens: "Milk",
  },
  {
    id: "4",
    name: "Salted Butter",
    category: "Butter",
    price: 5.29,
    stock: 40,
    image: "/placeholder.svg?height=300&width=300",
    description: "Premium salted butter from grass-fed cows",
    origin: "Vermont",
    allergens: "Milk",
  },
  {
    id: "5",
    name: "Brie Cheese",
    category: "Cheese",
    price: 8.99,
    stock: 25,
    image: "/placeholder.svg?height=300&width=300",
    description: "Soft and creamy brie with edible rind",
    origin: "France",
    allergens: "Milk",
  },
  {
    id: "6",
    name: "Chocolate Milk",
    category: "Milk",
    price: 3.99,
    stock: 35,
    image: "/placeholder.svg?height=300&width=300",
    description: "Delicious chocolate-flavored milk",
    origin: "Local Farms",
    allergens: "Milk",
  },
  {
    id: "7",
    name: "Strawberry Yogurt",
    category: "Yogurt",
    price: 2.99,
    stock: 60,
    image: "/placeholder.svg?height=300&width=300",
    description: "Creamy yogurt with real strawberry pieces",
    origin: "California",
    allergens: "Milk",
  },
  {
    id: "8",
    name: "Blue Cheese",
    category: "Cheese",
    price: 7.49,
    stock: 20,
    image: "/placeholder.svg?height=300&width=300",
    description: "Strong and tangy blue cheese",
    origin: "Italy",
    allergens: "Milk",
  },
  {
    id: "9",
    name: "Heavy Cream",
    category: "Cream",
    price: 4.49,
    stock: 30,
    image: "/placeholder.svg?height=300&width=300",
    description: "Rich and thick heavy cream for cooking and baking",
    origin: "Local Farms",
    allergens: "Milk",
  },
  {
    id: "10",
    name: "Cottage Cheese",
    category: "Cheese",
    price: 3.79,
    stock: 40,
    image: "/placeholder.svg?height=300&width=300",
    description: "Creamy cottage cheese with small curds",
    origin: "Michigan",
    allergens: "Milk",
  },
  {
    id: "11",
    name: "Almond Milk",
    category: "Plant-Based",
    price: 4.29,
    stock: 55,
    image: "/placeholder.svg?height=300&width=300",
    description: "Dairy-free milk alternative made from almonds",
    origin: "California",
    allergens: "Tree Nuts",
  },
  {
    id: "12",
    name: "Gouda Cheese",
    category: "Cheese",
    price: 6.49,
    stock: 35,
    image: "/placeholder.svg?height=300&width=300",
    description: "Semi-hard Dutch cheese with a mild flavor",
    origin: "Netherlands",
    allergens: "Milk",
  },
  {
    id: "13",
    name: "Sour Cream",
    category: "Cream",
    price: 2.99,
    stock: 45,
    image: "/placeholder.svg?height=300&width=300",
    description: "Tangy sour cream for toppings and dips",
    origin: "Local Farms",
    allergens: "Milk",
  },
  {
    id: "14",
    name: "Oat Milk",
    category: "Plant-Based",
    price: 4.49,
    stock: 50,
    image: "/placeholder.svg?height=300&width=300",
    description: "Creamy dairy-free milk alternative made from oats",
    origin: "Sweden",
    allergens: "Gluten",
  },
  {
    id: "15",
    name: "Mozzarella Cheese",
    category: "Cheese",
    price: 5.99,
    stock: 40,
    image: "/placeholder.svg?height=300&width=300",
    description: "Fresh Italian cheese perfect for pizza and salads",
    origin: "Italy",
    allergens: "Milk",
  },
]

